import { describe, expect, it } from 'vitest'
import type { CardExpense, Payment } from '../types/database'
import {
  buildSubscriptionPaymentDraft,
  buildSubscriptionSummary,
  subscriptionAlreadyPlanned,
  type SubscriptionItem,
} from './subscriptions'

const base = { user_id: 'u', created_at: '2026-01-01', updated_at: '2026-01-01' }

function expense(id: string, spent_at: string, amount: number, description = 'İGDAŞ'): CardExpense {
  return { ...base, id, card_id: 'c', statement_archive_id: null, spent_at, amount, description, category: 'Fatura', installment_count: 1, installment_amount: amount, status: 'posted', posted_at: `${spent_at}T10:00:00Z`, note: null, transaction_fingerprint: null, source: null }
}

function payment(overrides: Partial<Payment> = {}): Payment {
  return { ...base, id: 'p', title: 'İGDAŞ', category: 'Fatura', amount: 200, amount_status: 'exact', due_date: '2026-07-01', status: 'bekliyor', payment_method: 'bank_auto', recurrence: 'monthly', recurrence_day: 1, recurrence_end_date: null, auto_source_card_id: 'c', note: null, ...overrides }
}

describe('buildSubscriptionSummary', () => {
  it('uses only recent observations when calculating consistency and amount', () => {
    const result = buildSubscriptionSummary([
      expense('old', '2025-10-01', 100),
      expense('new-1', '2026-05-01', 200, 'igdaş'),
      expense('new-2', '2026-06-01', 200, 'igdaş'),
      expense('new-3', '2026-07-01', 200),
    ], [], null, new Date(2026, 6, 15))
    expect(result.items).toHaveLength(1)
    expect(result.items[0]!.amount).toBe(200)
  })

  it('2 ay tekrar abonelik sayılmaz (OPET benzeri false positive regresyonu)', () => {
    const result = buildSubscriptionSummary([
      expense('fuel-1', '2026-06-10', 2245.4, 'BUPET BURSA OPET'),
      expense('fuel-2', '2026-07-11', 2245.4, 'BUPET BURSA OPET'),
    ], [], null, new Date(2026, 6, 15))
    expect(result.items).toHaveLength(0)
  })

  it('does not double count card expenses generated by a card-funded recurring payment', () => {
    const result = buildSubscriptionSummary([
      { ...expense('e1', '2026-06-01', 200), note: 'Odeme kaydindan olusturuldu. Vade: 2026-06-01' },
      { ...expense('e2', '2026-07-01', 200), note: 'Odeme kaydindan olusturuldu. Vade: 2026-07-01' },
    ], [payment()], 10000, new Date(2026, 6, 15))
    expect(result.items).toHaveLength(1)
    expect(result.items[0]!.source).toBe('recurring_payment')
    expect(result.monthlyTotal).toBe(200)
  })

  it('does not double count an SMS expense reconciled with a differently named recurring payment', () => {
    const result = buildSubscriptionSummary([
      { ...expense('e1', '2026-05-08', 385, 'BUSKİ'), note: 'Ödeme kaydıyla SMS üzerinden eşleştirildi. Vade: 2026-05-08' },
      { ...expense('e2', '2026-06-08', 385, 'BUSKİ'), note: 'Ödeme kaydıyla SMS üzerinden eşleştirildi. Vade: 2026-06-08' },
      { ...expense('e3', '2026-07-08', 385, 'BUSKİ'), note: 'Ödeme kaydıyla SMS üzerinden eşleştirildi. Vade: 2026-07-08' },
    ], [payment({ title: 'Su', amount: 385, recurrence_day: 8, due_date: '2026-08-08' })], 10000, new Date(2026, 6, 15))

    expect(result.items).toHaveLength(1)
    expect(result.items[0]).toMatchObject({ source: 'recurring_payment', title: 'Su', amount: 385 })
    expect(result.monthlyTotal).toBe(385)
  })

  it('tekrar satırı kartını ve ay gününü taşır (Planla dönüşümü için)', () => {
    const result = buildSubscriptionSummary([
      expense('s1', '2026-05-14', 200, 'SPOTIFY'),
      expense('s2', '2026-06-14', 200, 'SPOTIFY'),
      expense('s3', '2026-07-14', 200, 'SPOTIFY'),
    ], [], null, new Date(2026, 6, 15))
    expect(result.items[0]).toMatchObject({ sourceCardId: 'c', recurrenceDay: 14 })
  })
})

function radarItem(overrides: Partial<SubscriptionItem> = {}): SubscriptionItem {
  return {
    id: 'expense:spotify',
    source: 'recurring_expense',
    title: 'SPOTIFY',
    category: 'Abonelik',
    amount: 200,
    monthCount: 3,
    isActive: true,
    sourceCardId: 'kredi',
    recurrenceDay: 14,
    ...overrides,
  }
}

describe('buildSubscriptionPaymentDraft', () => {
  const isCredit = (cardId: string) => cardId === 'kredi'

  it('kredi kartı kaynaklı satırdan bank_auto + kart bağlı aylık taslak üretir', () => {
    const draft = buildSubscriptionPaymentDraft(radarItem(), isCredit, new Date('2026-08-25T12:00:00'))
    expect(draft).toMatchObject({
      title: 'SPOTIFY',
      category: 'Dijital üyelik',
      amount: 200,
      amount_status: 'estimated',
      due_date: '2026-09-14', // bu ayın 14'ü geçti → gelecek ay
      payment_method: 'bank_auto',
      auto_source_card_id: 'kredi',
      recurrence: 'monthly',
      recurrence_day: 14,
    })
  })

  it('tekrar günü henüz gelmediyse vade bu ayda kalır; kısa aya kırpılır', () => {
    expect(buildSubscriptionPaymentDraft(radarItem(), isCredit, new Date('2026-08-10T12:00:00'))!.due_date).toBe('2026-08-14')
    expect(
      buildSubscriptionPaymentDraft(radarItem({ recurrenceDay: 31 }), isCredit, new Date('2027-02-05T12:00:00'))!.due_date,
    ).toBe('2027-02-28')
  })

  it('banka kartı kaynaklı ve planlı-ödeme satırlarında susar (çift sayma)', () => {
    expect(buildSubscriptionPaymentDraft(radarItem({ sourceCardId: 'banka' }), isCredit)).toBeNull()
    expect(buildSubscriptionPaymentDraft(radarItem({ source: 'recurring_payment' }), isCredit)).toBeNull()
  })
})

describe('subscriptionAlreadyPlanned', () => {
  it('aynı başlıklı aylık plan varsa true', () => {
    expect(subscriptionAlreadyPlanned(radarItem(), [payment({ title: 'Spotify' })])).toBe(true)
    expect(subscriptionAlreadyPlanned(radarItem(), [payment({ title: 'Netflix' })])).toBe(false)
    expect(subscriptionAlreadyPlanned(radarItem(), [payment({ title: 'Spotify', recurrence: 'none' })])).toBe(false)
  })
})
