import { describe, expect, it } from 'vitest'
import type { CardExpense, Payment } from '../types/database'
import { buildSubscriptionSummary } from './subscriptions'

const base = { user_id: 'u', created_at: '2026-01-01', updated_at: '2026-01-01' }

function expense(id: string, spent_at: string, amount: number, description = 'İGDAŞ'): CardExpense {
  return { ...base, id, card_id: 'c', statement_archive_id: null, spent_at, amount, description, category: 'Fatura', installment_count: 1, installment_amount: amount, status: 'posted', posted_at: `${spent_at}T10:00:00Z`, note: null, transaction_fingerprint: null }
}

function payment(overrides: Partial<Payment> = {}): Payment {
  return { ...base, id: 'p', title: 'İGDAŞ', category: 'Fatura', amount: 200, amount_status: 'exact', due_date: '2026-07-01', status: 'bekliyor', payment_method: 'bank_auto', recurrence: 'monthly', recurrence_day: 1, recurrence_end_date: null, auto_source_card_id: 'c', note: null, ...overrides }
}

describe('buildSubscriptionSummary', () => {
  it('uses only recent observations when calculating consistency and amount', () => {
    const result = buildSubscriptionSummary([
      expense('old', '2025-10-01', 100),
      expense('new-1', '2026-06-01', 200, 'igdaş'),
      expense('new-2', '2026-07-01', 200),
    ], [], null, new Date(2026, 6, 15))
    expect(result.items).toHaveLength(1)
    expect(result.items[0]!.amount).toBe(200)
  })

  it('does not double count card expenses generated by a card-funded recurring payment', () => {
    const result = buildSubscriptionSummary([
      { ...expense('e1', '2026-06-01', 200), note: 'Odeme kaydindan olusturuldu. Vade: 2026-06-01' },
      { ...expense('e2', '2026-07-01', 200), note: 'Odeme kaydindan olusturuldu. Vade: 2026-07-01' },
    ], [payment()], 10000, new Date(2026, 6, 15))
    expect(result.items).toHaveLength(1)
    expect(result.items[0]!.source).toBe('recurring_payment')
    expect(result.monthlyTotal).toBe(200)
  })
})
